version: '3.8'

services:
  trading-bot:
    build: .
    container_name: autonomous-trading-bot
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
    networks:
      - trading-network
    ports:
      - "8000:8000"

  postgres:
    image: postgres:15-alpine
    container_name: trading-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: trading_user
      POSTGRES_PASSWORD: ${DB_PASSWORD:-changeme123}
      POSTGRES_DB: trading_bot
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - trading-network
    ports:
      - "5433:5432"  # Changed to 5433 to avoid conflict with local PostgreSQL

  redis:
    image: redis:7-alpine
    container_name: trading-cache
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    networks:
      - trading-network
    ports:
      - "6379:6379"

networks:
  trading-network:
    driver: bridge

volumes:
  postgres-data:
  redis-data:
